name: "Flit Soft Pipeline Switch"
description: "Prevents multiples scheduled pipeline to run duplicate tasks on different mirror repo"
inputs:
  project:
    description: "The Project id"
    required: true
  type:
    description: "Must be either ci or cd"
    required: true
  value:
    description: "Value of ci or cd"
    required: true
branding:
  icon: cloud
  color: orange
runs:

  using: "composite"
  steps:
    - name: "Flutter setup"
      shell: bash
      run: |
        npm install
        node index.js --project ${{ inputs.project }} -type ${{ inputs.type }}  --value=${{ inputs.value }}
