flit_ride:
#  ci: github.com/flitsoft/flitride
  ci: github.com/flitride/flit_ride
  cd: codemagic.io/flitsoft.flitride

tolotra.mg:
  ci: github.com/tolotra-mg/tolotra_mg
  cd: codemagic.io/flitsoft.tolotramg

booking:
  ci: github.com/flit-Booking/booking
  cd: codemagic.io/flitsoft.flitbooking

