flit_ride:
  ci: https://github.com/Flit-Soft-Team-F/flitride
  # ci: https://github.com/flitride/flit_ride
  cd: codemagic.io/flitsoft.flitride

flit_ride_server:
  ci: https://github.com/flitride/flit_ride_server
  cd: no_cd

flit_ride_model:
  ci: https://github.com/flitride/flit_ride_model
  cd: no_cd

tolotra.mg:
  ci: https://github.com/Tolotra-mg/tolotra_mg
  # ci: https://github.com/flitsoft/tolotra.mg
  # ci: https://github.com/flitride/tolotra.mg
  cd: codemagic.io/flitsoft.tolotramg

booking:
  ci: https://github.com/Flit-Booking/flit_booking
  # ci: https://github.com/flitsoft/booking
  # ci: https://github.com/flitride/booking
  cd: codemagic.io/flitsoft.flitbooking

transaction_mvola:
  ci: https://github.com/Flit-Soft-Team-E/transaction_mvola
  # ci: https://github.com/Flit-Soft-Team-A/transaction_mvola
  cd: no_cd

facebook_scrape:
  ci: https://github.com/Flit-Soft-Team-C/facebook_scrape
  cd: no_cd

e2e_testing:
  ci: https://github.com/Flit-Soft-Team-E/pipeline_e2e_testing
  # ci: https://github.com/Flit-Soft-Team-B/pipeline_e2e_testing
  # ci: https://github.com/Flit-Soft-Team-D/pipeline_e2e_testing
  cd: no_cd
