flit_ride:
  ci: https://github.com/flitride/flit_ride
  cd: codemagic.io/flitsoft.flitride

flit_ride_server:
  ci: https://github.com/flitride/flit_ride_server
  cd: no_cd

tolotra.mg:
  ci: https://github.com/Tolotra-mg/tolotra_mg
  cd: codemagic.io/flitsoft.tolotramg

booking:
  ci: https://github.com/Flit-Booking/flit_booking
  cd: codemagic.io/flitsoft.flitbooking

transaction_mvola:
  ci: https://github.com/Flit-Soft-Team-E/transaction_mvola
  cd: no_cd

facebook_scrape:
  ci: https://github.com/Flit-Soft-Team-C/facebook_scrape
  cd: no_cd

e2e_testing:
  ci: https://github.com/Flit-Soft-Team-E/pipeline_e2e_testing
  cd: no_cd

